// export const productCreateFormInitialValues = {
//     title: '',
//     displayTitle: '',
//     color: '',
//     video: '',
//     description: '',
//     category: null,
//     brand: null,
//     price: 0,
//     subs: [],
//     quantity: 0,
//     images: [],
//     powerRequirements: {
//         voltage: '',
//         amperage: '',
//         frequency: '',
//         power: '',
//         powerSupplyType: '',
//         plugType: '',
//         batteryRequirements: '',
//         powerManagementFeatures: '',
//     },
//     dimensions: {
//         length: '',
//         width: '',
//         height: '',
//         weight: '',
//     },
//     specifications: {
//         processor: '',
//         model: '',
//         ram: {
//             size: '',
//             unit: '',
//         },
//         storage: {
//             type: '',
//             size: '',
//             unit: '',
//         },
//         display: {
//             size: '',
//             unit: '',
//             resolution: '',
//         },
//
//         battery: {
//             capacity: '',
//             unit: '',
//         },
//         os: '',
//         sim: '',
//         connectivity: '',
//         audioFeatures: '',
//     },
//     warranty: {
//         duration: '',
//         details: '',
//     },
// };

export const productCreateFormInitialValues = {
    title: '',
    displayTitle: '',
    color: '',
    description: '',
    category: '',
    brand: '',
    price: 0,
    subs: [],
    quantity: 0,
    images: [],
    powerRequirements: {
        voltage: '3.7 V',
        amperage: '2 A',
        frequency: '60 Hz',
        power: '5 W',
        powerSupplyType: 'Battery',
        plugType: 'USB Type-C',
        batteryRequirements: '3000 mAh',
        powerManagementFeatures: 'Fast charging',
    },
    dimensions: {
        length: '5.7 inch',
        width: '2.7 inch',
        height: '0.3 inch',
        weight: '160 g',
    },
    specifications: [],
    warranty: {
        duration: 12,
        details: 'Limited warranty covering manufacturing defects.',
    },
};
